### ISSUE TITLE
Windows v1.6 - 'PS5 Features' Crashing

### ISSUE THREAD

**Issue by Malnoth** [streetpea/chiaki4deck#177] opened 2024-01-16 04:41 UTC
Windows v1.6:

If 'PS5 Features:' is enabled in settings, remote play crashes immediately. 
Log message "Reported Application Reason: 0x80108b15 (Remote Play on Console crashed)". 
A PS5 restart is needed in order to connect again.

**Comment by streetpea** [comment] 2024-01-16 07:56
This is a duplicate of #38

**Closed by streetpea** 2024-01-16 07:56 UTC
