### ISSUE TITLE
Hardware decode problem vaapi

### ISSUE THREAD

**Issue by preacha** [streetpea/chiaki4deck#63] opened 2023-04-17 15:50 UTC
Hello,

since today I get this error again.

![image](https://user-images.githubusercontent.com/7067861/232540934-03920d09-0346-46dd-990b-e87113af5d48.png)

**Comment by Razen1994** [comment] 2023-04-17 21:51
Same here. Started it up and got the exact same error. I guess some update broke something

**Comment by znre** [comment] 2023-04-18 01:30
+1 same here

**Comment by EXCADOGOD** [comment] 2023-04-18 03:41
I have the same question

**Comment by aarontsosa** [comment] 2023-04-18 04:33
Seeing the same issue

**Comment by helliongame** [comment] 2023-04-18 09:51
same here , yesterday evening , i update all discovery updates on desk mode. This morning , after restart  , i have the same described issue. 

Could you do something to fix it?

Greetings

**Comment by aronsr1** [comment] 2023-04-18 19:10
I tried going onto beta and then back to stable 3.4.6. Also experiencing the same. So frustrating as I primarily use the steam deck as a streaming device

**Comment by aronsr1** [comment] 2023-04-18 19:11
> I tried going onto beta and then back to stable 3.4.6. Also experiencing the same. So frustrating as I primarily use the steam deck as a streaming device

This same issue applies to Moonlight too

**Comment by ranger149** [comment] 2023-04-18 19:13
I can confirm the issue regarding moonlight occurs regardless if you are on the stable, beta, or preview builds. Further, this issue does not occur with the AppImage version of moonlight, so it appears to be an issue with Flatpak drivers.

**Comment by helliongame** [comment] 2023-04-18 20:41
@ranger149 they close your case because they said that is a flatpak package

**Comment by ranger149** [comment] 2023-04-18 20:57
> @ranger149 they close your case because they said that is a flatpak package issue

Yeah, I've tried submitting a bug with Flatpak. Hopefully it's the right location now.

**Comment by ranger149** [comment] 2023-04-19 20:26
You are correct. They just released an update to the KDE Runtime and it has since resolved the issue. All anyone needs to do is update their KDE runtime through the KDE Discover store. Please close this issue, thank you.

**Closed** 2023-04-19 20:42 UTC
