### ISSUE TITLE
Microphone undetected

### ISSUE THREAD

**Issue by Minolito** [streetpea/chiaki4deck#96] opened 2023-11-18 01:30 UTC
Hello,

I am currently using the 1.4.1 version of chiaki4deck on steam deck, and despite the addition of microphone support I am still unable to make it work.

I am able to unmute the microphone with ctrl+m, but my voice isn't detected. I tested the microphone in both vocal chat and detection settings without success.

In other softwares and in desktop mode however, the microphone is working without issue.

Do you know what could be the issue here?

Thanks a ton for your work on this project!

**Comment by streetpea** [comment] 2023-11-18 03:03
Have you tried it with the built-in microphone on the Steam Deck? It's possible whatever microphone you are using isn't being picked up as the default microphone. In the Chiaki4deck settings is the microphone set to Auto?

**Comment by Minolito** [comment] 2023-11-18 03:11
I tried with both the built-in microphone and a headset featuring a
microphone, same result. And yes the microphone is set to auto the settings.

**Comment by streetpea** [comment] 2023-11-18 03:31
The internal microphone works fine for me on auto are you also using a PS5?

**Comment by Minolito** [comment] 2023-11-18 10:52
Yes, I'm also using a PS5. I wonder what could be the issue here...

**Comment by Minolito** [comment] 2023-11-18 11:32
I also tried on both game mode and desktop mode, to no avail. Maybe I could
try with another build ?

Le sam. 18 nov. 2023 à 11:52, Moktar Dubois ***@***.***> a
écrit :

**Comment by Minolito** [comment] 2023-11-18 12:02
I forgot to mention that I am using the latest stable version of SteamOS,
3.5.5 and I haven't tried in previous releases. Could it be linked to the
issue ?

Le sam. 18 nov. 2023 à 12:32, Moktar Dubois ***@***.***> a
écrit :

**Comment by Minolito** [comment] 2023-11-18 16:37
Yes, I'm also using a PS5. 

I tried both game mode and desktop mode, to no avail.

I forgot to mention that I am using the latest stable version of SteamOS (3.5.5) and I haven't tried previous releases. 

The sound test in PS5 settings is working just fine with the Dualsense directly connected to the PS5, but the bars are not being filled with the Deck microphone via Chiaki...

**Comment by streetpea** [comment] 2023-11-18 22:19
When in desktop mode when you unmute the microphone do you see a microphone appear? It should be in the bottom right hand corner with the error icons can you try clicking on that. It's possible it's stuck in muted mode.

**Comment by Minolito** [comment] 2023-11-18 22:33
Yes, the icon does appear when I unmute the microphone with the following message when I hover on it: "QtPulseAudio:2 is using the microphone (ACP/ACP3X/ACP6X Audio Coprocessor Headset Microphone + Internal Microphone)"

However it's not muted and works fine with other softwares.

**Comment by Minolito** [comment] 2023-11-18 22:43
I noted something interesting: while the microphone is being used in another software / browser, it is detected by chiaki (bars are filled in the test settings).

I tried testing the microphone with the following website: https://mictests.com and once the icon showed up on the taskbar, it started being detected by Chiaki. However, once the web browser it closed, it stops working on Chiaki as well.

**Comment by streetpea** [comment] 2023-11-18 22:47
I wonder if this is related: in the steam deck preview channel the latest update 3.5.6 the patch notes are "Fixed additional cases where the internal microphone wouldn't work"

**Comment by Minolito** [comment] 2023-11-18 23:06
I've seen the patch notes, but it looks like it's referring to cases where the microphone is not working altogether.

And yes, the sound test does work if I use the microphone with another app.

**Comment by streetpea** [comment] 2023-11-18 23:09
I'm on the preview branch now but tested on stable before release and it worked fine. I'll switch to stable now and check if it's still working.

**Comment by streetpea** [comment] 2023-11-18 23:17
I switched to the stable channel and it no longer works so I think it is a regression with 3.5.5 that is fixed in 3.5.6

**Comment by streetpea** [comment] 2023-11-18 23:44
I switched back to preview and downloaded the 3.5.6 beyond stable update and it works again. This seems to be due to a SteamOS bug.

**Comment by Minolito** [comment] 2023-11-19 20:07
I updated to the preview channel with SteamOS 3.5.6 and looks like it's working just fine.

So this microphone issue is only occuring on the 3.5.5 version on the stable channel.

**Comment by streetpea** [comment] 2023-11-19 21:30
Since this is a SteamOS issue with mic support it should fix itself with the updates. I'll leave this issue open until the fix makes its way into the stable branch so that if someone runs into the problem, they can see this issue for reference.

**Comment by johnhste** [comment] 2023-11-29 04:03
I am not sure if this is the write place for this.
when I am using the mic it will work for a while then randomly stop I am on steamos 3.5.7.

**Comment by streetpea** [comment] 2023-11-29 04:55
@johnhste given you aren't accidentally muting the microphone (which is unlikely) it seems that there would be 1 of 3 causes for this ... 1. the mic stops recording audio (would probably be a steamos bug maybe linked to the fixed bug) ... 2. The connection stops sending audio packets (this is very unlikely as unless you use mute it uses the same logic to send packets so there isn't really a mechanism for it to stop sending them) 3. The PlayStation console stops responding to the sent packets (this would imply some other message needs to be sent to the PlayStation after x minutes to continue accepting packets). 

I can eliminate 2 since there isn't a code path where this would happen. I can create a flatpak that logs when it sends audio messages to test whether it's 1 or 3 if you are willing to run it and then you could look at the logs and report back whether it is still sending audio messages when the audio cuts out or if it has stopped @johnhste.

**Comment by johnhste** [comment] 2023-11-29 04:58
I am very willing to help.

**Comment by johnhste** [comment] 2023-11-30 03:16
I don't see icon and no audio

**Comment by streetpea** [comment] 2023-11-30 03:17
Is this on Steam Deck and you are using the toggle mic key in the chiaki4deck + mic controller layout?

**Comment by streetpea** [comment] 2023-11-30 03:17
How do you get audio to begin with if you can't toggle the mic?

**Comment by johnhste** [comment] 2023-11-30 03:19
yes I get a notification that the remote Mic is connected but no mute unmute icon

**Comment by streetpea** [comment] 2023-11-30 03:22
You can also check the current state of the mic by going to the home menu and clicking on the mic and see if it's muted or unmuted.

**Comment by johnhste** [comment] 2023-11-30 03:29
I am sorry on the ps or the steam deck

**Comment by streetpea** [comment] 2023-11-30 03:30
On the steam deck in the stream window

**Comment by streetpea** [comment] 2023-11-30 04:09
@johnhste  I uploaded a build you can use for testing download this file 
[io.github.streetpea.Chiaki4deck-mic.txt](https://github.com/streetpea/chiaki4deck/files/13508227/io.github.streetpea.Chiaki4deck-mic.txt)
 and rename it to **io.github.streetpea.Chiaki4deck-mic.flatpakref** instead of .txt (I changed it to .txt for Github to allow me to upload it here) and then use the following in the directory where its located:
```
flatpak install --user -y io.github.streetpea.Chiaki4deck-mic.flatpakref
```
After running this file once to test with:
```
flatpak run io.github.streetpea.Chiaki4deck-mic
```
replace the config file with a copy of your chiaki4deck config file with:
```
cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf ~/.var/app/io.github.streetpea.Chiaki4deck-mic/config/Chiaki/Chiaki.conf
```
Finally, add it to Steam as a non-steam game if you want to use it in game mode during testing.

**Comment by johnhste** [comment] 2023-11-30 04:14
i got an error

(1)(deck@steamdeck ~)$ cd Downloads/
(deck@steamdeck Downloads)$ flatpak install --user -y io.github.streetpea.Chiaki4deck-mic.flatpakref
error: No such ref 'app/io.github.streetpea.Chiaki4deck-mic/x86_64/chiaki4deck' in remote chiaki4deck-mic-origin
(1)(deck@steamdeck Downloads)$ flatpak install --user -y io.github.streetpea.Chiaki4deck-mic.flatpakref
error: No such ref 'app/io.github.streetpea.Chiaki4deck-mic/x86_64/chiaki4deck' in remote chiaki4deck-mic-origin
(1)(deck@steamdeck Downloads)$

**Comment by johnhste** [comment] 2023-11-30 04:19
i haven't seen any icon for mic in the stream window.
![Screenshot_20231129_215512e](https://github.com/streetpea/chiaki4deck/assets/68291734/6ba32253-3890-492f-8096-3ae50577f50b)
![Screenshot_20231129_215403](https://github.com/streetpea/chiaki4deck/assets/68291734/739bd7e1-34b0-4646-a512-143dad015d74)
i attached  screen shots for my settings.

**Comment by streetpea** [comment] 2023-11-30 04:31
@johnhste it looks like you have a ps4 ... I'm getting the icons on a PS5. It's possible they don't show on a PS4. The icon for mic I see is when I'm running chiaki4deck and go to the Playstation home menu. There is a mic button in the home menu itself that I can see on the console and on the stream of the console.

**Comment by johnhste** [comment] 2023-11-30 04:52
i have been messing with settings in chiaki and testing.
here are a bunch more screen shots. 
![Screenshot_20231129_224604](https://github.com/streetpea/chiaki4deck/assets/68291734/feb8d18c-aad4-4a20-a9cf-fad00ae11bc6)
![Screenshot_20231129_224629](https://github.com/streetpea/chiaki4deck/assets/68291734/6c825169-d379-49df-86ed-78a6301ccadb)
![Screenshot_20231129_224812](https://github.com/streetpea/chiaki4deck/assets/68291734/73ba7f10-1638-4e53-9982-7fecc5f13062)
![Screenshot_20231129_224856](https://github.com/streetpea/chiaki4deck/assets/68291734/d13a61cb-b263-48d0-a1b1-de6b81fff7e8)
![Screenshot_20231129_224950](https://github.com/streetpea/chiaki4deck/assets/68291734/25263dad-8b3a-4da0-be61-28b23b073ff9)

**Comment by johnhste** [comment] 2023-11-30 05:01
in reference to my screen shots above they are not in order sorry for that but i had it set for auto mic and no audio then i decided to try all the options again and got it on the pulse one for some reason it said alsa plugin in the mic hover indicator then it just quit no change from my end that i could tell. then i reconnected and it worked again.

**Comment by streetpea** [comment] 2023-11-30 05:05
@johnhste if you run the commands I posted again it should work now.

**Comment by johnhste** [comment] 2023-11-30 05:08
ok I will do more tests tomorrow.

**Comment by johnhste** [comment] 2023-12-01 02:30
the mic stopped on the ps when the frames also hitched around [2023-11-30 18:40:37:071071]

**Comment by streetpea** [comment] 2023-12-01 02:41
ok and does it usually cut out this fast for you @johnhste?

**Comment by johnhste** [comment] 2023-12-01 02:58
no i just had an interesting thought i am wondering if it isn't a bandwidth issue with my wifi where chiaki is sending the audio but the ps isn't seeing it for some reason. i just gamed for a while with no issue. i have been making an audio party and using my phone for monitoring.

**Comment by johnhste** [comment] 2023-12-01 03:05
the though came to me because my dog wanted out so i took him and the wifi jumped to my garage acesspoint and the video recovered but the audio didn't on the ps. but the packets were being sent. according to chiaki. i am going to attach the log. the part of interest is at [2023-11-30 18:31:55:678678]
[chiaki_session_2023-11-30_18-21-28-827827walked dog outside.log](https://github.com/streetpea/chiaki4deck/files/13520185/chiaki_session_2023-11-30_18-21-28-827827walked.dog.outside.log)

**Comment by streetpea** [comment] 2023-12-02 21:56
Since stable channel is now 3.5.7 the mic not being detected has been patched so I'm closing this issue @johnhste I created a new issue for your problem #106

**Closed** 2023-12-02 21:56 UTC
