### ISSUE TITLE
1.7 update won’t work on Steamdeck

### ISSUE THREAD

**Issue by parkercd** [streetpea/chiaki4deck#329] opened 2024-05-13 20:44 UTC
Chiaki4deck 1.7 update. I can launch the app wake my ps5 but when I select it to start stream I go back to the steam library. 

I also tried in desktop as well same issue. Last version was working perfectly used every day. How do I go back to 1.66 can’t find a way of downloading it. I download my original through the Linux store is desktop mode

**Comment by parkercd** [comment] 2024-05-13 21:03
Also tried to add proton compatibility layer but won't load app at all if I do this. I can go into settings etc but as soon as I select console to start stream screen goes dark then back back in steam OS. My steam OS is on the latest stable version

**Comment by streetpea** [comment] 2024-05-13 22:27
Can you launch via the konsole `flatpak run io.github.streetpea.Chiaki4deck` and post the output in the konsole?

**Comment by streetpea** [comment] 2024-05-13 22:29
Also here’s how to downgrade

**Comment by streetpea** [comment] 2024-05-14 01:37
@parkercd can you try manually setting your hw decoder to none and then to vaapi and then try again? Vulkan got disabled in the flatpak when ffmpeg was upgraded to version 7.0 since the Vulkan headers weren’t new enough and if you have it set as the decoder in your settings it will cause a crash as soon as it tries to get loaded (upon launching the stream session)

**Comment by Adagium42** [comment] 2024-05-14 06:16
I can confirm. _Chiaki4Deck_ was working perfectly for me yesterday and stopped working with the last update (1.7.0 Flatpak, Fedora 39). The software opens, but when selecting any of my consoles (PS4 and PS5) it crashes. I didn't identify the cause in the logs since the last thing the terminal reports is: 
> [I] Discovery Service detected new host with id [REDACTED] 

But from what has been discussed here, it indeed appears it's caused by Hardware Decoder. Before the update I was using _Vulkan_, which is no longer available. With the update, despite “_None_” being selected, it appears in the backend _Chiaki4Deck_ was still trying to use _Vulkan_. I changed it to _VA-API_ and it worked again, and then I changed it to _None_ and it continues to work. **It's solved** for me, without the need for a downgrade. 

Thank you for your amazing work, @streetpea. I'm now excited to test the remote connection without Port Forwarding.

**Comment by parkercd** [comment] 2024-05-14 14:59
Just tried this and worked like a treat, thanks again for the support

**Comment by berypurda** [comment] 2024-05-15 13:25
Hello, I am having the same issue, but I cannot even get into the settings of chiaki4deck.
Should I delete user data and then set HW encoding to none? 
If so, why is vulkan being removed?

**Comment by berypurda** [comment] 2024-05-15 13:39
Update: I deleted chiaki4deck and the user settings, reinstalled, tested local play, works, psn play also works.
Really nice job streetpea, you are the hero who doesn't wear a cape.


Just 1 question tho, this is the first time I'm hearing about vaapi, how is it compared to Vulkan?
Vulkan has been praised ever since it's release, and I've always used it everywhere I could.
Why has it been removed?

**Comment by streetpea** [comment] 2024-05-15 18:36
@berypurda it was removed accidentally when ffmpeg was upgraded as newer Vulkan headers were required than those available in the flatpak for that version of ffmpeg. Ffmpeg has been reverted to the older version until Vulkan is upgraded in the flatpak base to fix this. However, publishing flatpak builds on flathub is currently down for maintenance so the flatpak hasn’t been updated to reenable Vulkan decoder yet.

**Comment by streetpea** [comment] 2024-05-17 18:22
The flatpak on Flathub has now been rebuilt to include vulkan. You can update via the discover store. Closing...

**Closed by streetpea** 2024-05-17 18:22 UTC
