### ISSUE TITLE
Stretch key does not work half the time.

### ISSUE THREAD

**Issue by XarceChronus** [streetpea/chiaki4deck#48] opened 2023-02-12 16:43 UTC
Using a community layout to assign the stretch key to back buttons, for whatever reason they do not work and it's seemingly random when they do work..
I have no idea how I managed to get them functioning last time but it really seems like most of the time these function keys do not work.
Anything involving the control key plus another key usually does not work.. unless it's The PlayStation button..

Is it possible to reassign these function keys so that they don't require holding a second button? It would be nice if stretch was just "S"

Either that or these functions just don't work half the time regardless

**Comment by streetpea** [comment] 2023-02-12 19:29
That is strange I use it consistently and have yet to have it fail on me…

Having said that there is a scenario where using stretch will have no effect (I.e., it will technically work but not change the image), which is when the window is set to the same aspect ratio as the stream. In that instance, the stretch to window has nothing to stretch to. 

In order to make sure this isn’t the case you would want to launch via the [automation](https://streetpea.github.io/chiaki4deck/setup/automation/) or go full screen first when using the gui as documented in the [Box titled “ Using These Options Without the Automation [Not Recommended] (click me to open)”](https://streetpea.github.io/chiaki4deck/updates/done/#3-view-modes-for-non-standard-screen-sizes) 

Note: you can also set the default launch option to stretch in the automation and it will launch with your screen stretched by default.

**Comment by XarceChronus** [comment] 2023-02-13 04:56
> That is strange I use it consistently and have yet to have it fail on me…
> 
> Having said that there is a scenario where using stretch will have no effect (I.e., it will technically work but not change the image), which is when the window is set to the same aspect ratio as the stream. In that instance, the stretch to window has nothing to stretch to. 
> 
> In order to make sure this isn’t the case you would want to launch via the [automation](https://streetpea.github.io/chiaki4deck/setup/automation/) or go full screen first when using the gui as documented in the [Box titled “ Using These Options Without the Automation [Not Recommended] (click me to open)”](https://streetpea.github.io/chiaki4deck/updates/done/#3-view-modes-for-non-standard-screen-sizes) 
> 
> Note: you can also set the default launch option to stretch in the automation and it will launch with your screen stretched by default.
> 
> @XarceChronus lmk your results from doing the above

It doesn't say anything about launch arguments or ensuring that it's running in full screen and not a window in your linked guide

**Comment by XarceChronus** [comment] 2023-02-13 05:19
I got a working by double tapping the screen with steam chord.
Thanks!

**Comment by streetpea** [comment] 2023-02-13 16:56
About the launch arguments, it’s not launch arguments per se. If you do the automation section (see https://streetpea.github.io/chiaki4deck/setup/automation/) and run the script in step 3 it will ask if you want stretch, Fullscreen or zoom. If you do the manual version of the automation it will have you do this manually. Since it’s expected for you to go through the different setup sections it should just work at that point. If for some reason you just skip that section (there is a disclaimer at the top of the section linking to the additional steps) which are pointed out in the link I have above. The problem is there isn’t really a good place in the guide to put it so I just put it there. 

From the guide: https://streetpea.github.io/chiaki4deck/updates/done/#3-view-modes-for-non-standard-screen-sizes
> If for some strange reason you want to launch chiaki4deck via the GUI instead of the automation (not recommended due to the items noted [here](https://streetpea.github.io/chiaki4deck/updates/done/#enabled-automated-launch)), it launches by default in a window matching the aspect ratio of the stream (i.e., 16:9). This means that the stream output exactly matches the stream window. In this scenario, there is nothing to stretch or zoom the stream output to because the stream output already perfectly matches with the stream window. If you want to stretch or zoom, you would need to first either:

> Adjust the window to a bigger or smaller size with your mouse in Desktop Mode (perhaps you want to use chiaki4deck as half of your screen in Desktop mode)
>OR
>Use fullscreen mode by:
>Pressing F11 (either directly in Desktop Mode or via a controller mapping in Game Mode)
OR
>Double clicking on the screen in Desktop Mode
Then, you could use stretch and/or zoom accordingly (i.e., Ctrl+S / Ctrl+Z or button mapped to them in game mode).

**Comment by streetpea** [comment] 2023-02-13 17:12
Glad you got it sorted :)

 If there’s anything else I can do to make this better / easier lmk. Otherwise, please close this issue if it solves your problem.

**Closed** 2023-02-22 06:24 UTC
